name: Build and Deploy Java Application

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - gh_runner_setup

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: System info
        run: |
          echo "## Runner Info" >> $GITHUB_STEP_SUMMARY
          echo "User: $(whoami)" >> $GITHUB_STEP_SUMMARY
          echo "PWD: $PWD" >> $GITHUB_STEP_SUMMARY
          echo "Disk:" >> $GITHUB_STEP_SUMMARY
          df -h >> $GITHUB_STEP_SUMMARY

      - name: Verify Java
        run: |
          java -version || echo "Java not installed"

      - name: Verify Maven
        run: |
          mvn -version || echo "Maven not installed"
